### ISSUE TITLE
Error while running test python client

### ISSUE THREAD

**Issue by klekkala** [jr-robotics/robo-gym-server-modules#1]
Hi!

While running the test MIR robot client program, I'm getting an error:
_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1602461115.459864652","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1602461115.459861937","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
 
On the client side, I get
Starting new Robot Server | Tentative 1
Starting new Robot Server | Tentative 2
Starting new Robot Server | Tentative 3
Starting new Robot Server | Tentative 4

Can you please help me out?
Thanks,
Kiran

**Comment by matteolucchi** [comment]
Hi Kiran,
can you give us some more details about the problem?

- which OS are you using?
- which version of python are you using?
- which test does return this error?

Thank you

**Comment by klekkala** [comment]
Hi Matteo,

I'm using Ubuntu 18.04, Python 3.7 and the error is returned by [this](https://github.com/jr-robotics/robo-gym-server-modules/blob/master/robo_gym_server_modules/server_manager/server.py#L91)

**Comment by matteolucchi** [comment]
This could be caused by two issues, either the Robot Server fails to start or there is some network error. 

When installing the [Robot Server Side](https://github.com/jr-robotics/robo-gym#robot-server-side) did you follow the Simplified Installation or the Standard Installation?
