### ISSUE TITLE
typo in /robo_gym_server_modules/server_manager/client.py", line 65

### ISSUE THREAD

**Issue by mphamhung** [jr-robotics/robo-gym-server-modules#2]
line 65:  raise RuntimeError('Failed {} tentatives of killing Robot Server'.forma(str(max_tentatives)))
AttributeError: 'str' object has no attribute 'forma'

FYI!

**Comment by matteolucchi** [comment]
Thank you very much for reporting that, we had that fixed already but I forgot to push it :)
